# Generated by Django 5.1.7 on 2025-03-20 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('player_cards', models.JSONField(default=list)),
                ('banker_cards', models.JSONField(default=list)),
                ('deck', models.JSONField(default=list)),
                ('player_score', models.IntegerField(default=0)),
                ('banker_score', models.IntegerField(default=0)),
                ('bet_on', models.CharField(choices=[('player', 'Player'), ('banker', 'Banker'), ('tie', 'Tie')], max_length=10)),
                ('bet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
