# Generated by Django 5.1.7 on 2025-03-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cards_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='shoe_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
