# Generated by Django 5.1.7 on 2025-03-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_cards_used_game_round_number_game_shoe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='bet_amount',
            new_name='buy_in',
        ),
        migrations.AddField(
            model_name='game',
            name='total_winnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
